// Developer Express Code Central Example:
// DXGrid Keyboard Navigation integration with AutoCompleteBox
// 
// Keyboard navigation support with custom editors in the DXGrid may be
// accomplished by setting a custom attached behavior -- available from the
// System.Windows.Interactivity library -- on the TableView to assign the a handler
// to the GridViewBase.EditorShowing
// (http://documentation.devexpress.com/#WPF/DevExpressXpfGridGridViewBase_ShowingEditortopic)
// event. There, you may handle the focus logic for the custom control.
// In the
// following example, we've handled the focus logic for the standard Slider control
// and the custom AutoCompleteBox from the WPF ToolKit -- WPF Toolkit - February
// 2010 Release (http://wpf.codeplex.com/releases/view/40535).
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E20032

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attachedBehaviorPolicy.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
